#ifndef DESPEC_ARRAY_SIZES
#define DESPEC_ARRAY_SIZES

#define SC41L_FatVME  48
#define SC41R_FatVME  49
#define FINGER_TAMEX_MODULES 4
#define FINGER_TAMEX_HITS    512

#define FATIMA_TAMEX_MODULES 5
#define FATIMA_TAMEX_HITS 256
#define FATIMA_TAMEX_CHANNELS 48
#define FAT_MAX_VME_DET  50

#define bPLASTIC_TAMEX_MODULES 4
#define bPLASTIC_TAMEX_HITS 256
#define bPLASTIC_TAMEX_CHANNELS 16

#define FIBRE_BOARD 3

#define GALILEO_MAX_DETS 9
#define GALILEO_CRYSTALS 3
#define GALILEO_MAX_HITS (GALILEO_MAX_DETS * GALILEO_CRYSTALS)
#define GALILEO_FEBEX_MODULES 3

#define AIDA_MAX_HITS 10000

#endif /* DESPEC_ARRAY_SIZES */
